// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0K3Zlx4U7wcy_SzPbvc1sRX8zz1Pa8Ec',
    appId: '1:899875993159:web:313b878334bf79459ca362',
    messagingSenderId: '899875993159',
    projectId: 're3plus-ee9e8',
    authDomain: 're3plus-ee9e8.firebaseapp.com',
    storageBucket: 're3plus-ee9e8.firebasestorage.app',
    measurementId: 'G-M8Y1N9RKM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNaWoIsLHe2IsVtPDhtn-6ygAEoAVKn0',
    appId: '1:899875993159:android:fd22ab3cc19cdb809ca362',
    messagingSenderId: '899875993159',
    projectId: 're3plus-ee9e8',
    storageBucket: 're3plus-ee9e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVX4xjoDtDAL2FQPDK5GZkAN6o-lI3m-s',
    appId: '1:899875993159:ios:c43eb3fe7587e9829ca362',
    messagingSenderId: '899875993159',
    projectId: 're3plus-ee9e8',
    storageBucket: 're3plus-ee9e8.firebasestorage.app',
    iosBundleId: 'com.example.bitsyre3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVX4xjoDtDAL2FQPDK5GZkAN6o-lI3m-s',
    appId: '1:899875993159:ios:c43eb3fe7587e9829ca362',
    messagingSenderId: '899875993159',
    projectId: 're3plus-ee9e8',
    storageBucket: 're3plus-ee9e8.firebasestorage.app',
    iosBundleId: 'com.example.bitsyre3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0K3Zlx4U7wcy_SzPbvc1sRX8zz1Pa8Ec',
    appId: '1:899875993159:web:e2ea5aa6693aff129ca362',
    messagingSenderId: '899875993159',
    projectId: 're3plus-ee9e8',
    authDomain: 're3plus-ee9e8.firebaseapp.com',
    storageBucket: 're3plus-ee9e8.firebasestorage.app',
    measurementId: 'G-WVEJTNPJTB',
  );
}
